name: Example workflow for Maven usng Snyk 
on:
  push:
    branches:
      - master
    paths:
      - "*"
      - "!README.md"
  schedule:
    # Run workflow once a day
    - cron: "0 0 * * *"
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
